/* ==========================================================================
   StudyLens — QUIZ_PROTOTYPE
   --------------------------------------------------------------------------
   Seed question bank. The backend can fully replace this later via
   GET /api/subjects/:key/quiz. Quiz shape:
   { questions: [{ q, opts:[4], correct, explain, level, topic }], time, outOf }
   `topic` powers weak-topic detection; `level` feeds adaptive difficulty.
   ========================================================================== */

const QUIZ_PROTOTYPE = {
  physics: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'A body of mass 2 kg is acted on by a net force of 8 N. What is its acceleration?',
        opts: ['2 m/s²', '4 m/s²', '16 m/s²', '0.25 m/s²'],
        correct: 1,
        explain: 'From Newton’s second law, a = F/m = 8/2 = 4 m/s². Force and acceleration are directly proportional for a fixed mass.',
        level: 'easy',
        topic: 'Mechanics',
      },
      {
        q: 'A ball is thrown vertically upward. At the highest point, its acceleration is:',
        opts: ['Zero', 'Downward, g', 'Upward, g', 'Depends on mass'],
        correct: 1,
        explain: 'At the top, velocity is zero but gravity still acts, so acceleration remains g downward — that is why it falls back down.',
        level: 'easy',
        topic: 'Mechanics',
      },
      {
        q: 'The dimensional formula of Planck’s constant (h) is:',
        opts: ['ML²T⁻¹', 'ML²T⁻²', 'MLT⁻²', 'ML²T⁻³'],
        correct: 0,
        explain: 'E = hν ⇒ h = E/ν. Energy is ML²T⁻² and frequency is T⁻¹, so h is ML²T⁻¹ (same as angular momentum).',
        level: 'moderate',
        topic: 'Mechanics',
      },
      {
        q: 'Two capacitors of 2 µF and 6 µF are connected in series. The equivalent capacitance is:',
        opts: ['8 µF', '1.5 µF', '4 µF', '12 µF'],
        correct: 1,
        explain: 'In series, 1/C = 1/2 + 1/6 = 4/6 ⇒ C = 1.5 µF. Series combination is always smaller than the smallest capacitor.',
        level: 'moderate',
        topic: 'Electromagnetism',
      },
      {
        q: 'A charge moving parallel to a magnetic field experiences a force:',
        opts: ['Maximum, perpendicular to v and B', 'Zero, since it is parallel', 'Proportional to charge', 'In the direction of B'],
        correct: 1,
        explain: 'F = qvB sinθ; with θ = 0°, sinθ = 0, so no force acts. Force is maximum when velocity is perpendicular to the field.',
        level: 'moderate',
        topic: 'Electromagnetism',
      },
      {
        q: 'In the photoelectric effect, increasing the intensity of light (frequency unchanged) increases:',
        opts: ['Kinetic energy of photoelectrons', 'Number of photoelectrons emitted', 'Threshold frequency', 'Wavelength of electrons'],
        correct: 1,
        explain: 'Intensity sets the number of photons, hence the photocurrent (number of electrons). Energy per electron depends only on frequency.',
        level: 'moderate',
        topic: 'Modern Physics',
      },
      {
        q: 'The refractive index of glass is 1.5. The critical angle at the glass–air interface is closest to:',
        opts: ['30°', '41.8°', '48.2°', '60°'],
        correct: 1,
        explain: 'sin C = 1/μ = 1/1.5 = 0.667 ⇒ C ≈ 41.8°. Beyond this angle, total internal reflection occurs.',
        level: 'hard',
        topic: 'Optics',
      },
      {
        q: 'For a reversible adiabatic process of an ideal gas, which quantity stays constant?',
        opts: ['PV', 'TV²', 'PVᵞ', 'P/T'],
        correct: 2,
        explain: 'Adiabatic reversible expansion obeys PVᵞ = constant (γ = Cp/Cv). PV = constant holds only for isothermal processes.',
        level: 'hard',
        topic: 'Thermodynamics',
      },
    ],
  },

  chemistry: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'The IUPAC name of CH₃CH₂COOH is:',
        opts: ['Propanoic acid', 'Ethanoic acid', 'Propanal', 'Methyl ethanoate'],
        correct: 0,
        explain: 'Three carbons with a –COOH group ⇒ propanoic acid. Two carbons would be ethanoic acid.',
        level: 'easy',
        topic: 'Organic Reactions',
      },
      {
        q: 'Which has the highest boiling point?',
        opts: ['Ethanol', 'Dimethyl ether', 'Propane', 'Acetaldehyde'],
        correct: 0,
        explain: 'Ethanol forms intermolecular hydrogen bonds, requiring more energy to separate molecules than the others.',
        level: 'easy',
        topic: 'Organic Reactions',
      },
      {
        q: 'The hybridisation of carbon in ethyne (C₂H₂) is:',
        opts: ['sp³', 'sp²', 'sp', 'dsp²'],
        correct: 2,
        explain: 'Ethyne has a triple bond: two σ bonds and two π bonds give sp hybridisation with a 180° linear geometry.',
        level: 'moderate',
        topic: 'Chemical Bonding',
      },
      {
        q: 'Which species is the strongest conjugate base?',
        opts: ['Cl⁻', 'NO₃⁻', 'F⁻', 'Br⁻'],
        correct: 2,
        explain: 'HF is the weakest acid among HCl, HNO₃, HF, HBr, so F⁻ holds its proton most strongly — strongest conjugate base.',
        level: 'moderate',
        topic: 'Chemical Bonding',
      },
      {
        q: 'For the reaction N₂ + 3H₂ ⇌ 2NH₃, the effect of increasing pressure is:',
        opts: ['Shifts equilibrium to the left', 'Shifts equilibrium to the right', 'No change', 'Shifts to right only with catalyst'],
        correct: 1,
        explain: 'Le Chatelier: 4 moles of gas become 2, so higher pressure favours the side with fewer moles — ammonia yield rises.',
        level: 'moderate',
        topic: 'Physical Chemistry',
      },
      {
        q: 'The number of moles of KMnO₄ required to oxidise one mole of Fe²⁺ in acidic medium is:',
        opts: ['1', '1.6', '0.2', '2'],
        correct: 2,
        explain: 'MnO₄⁻ gains 5 e⁻ (Mn⁷⁺→Mn²⁺) while Fe²⁺ loses 1 e⁻, so 1 mol MnO₄⁻ oxidises 5 mol Fe²⁺ — one fifth = 0.2 mol.',
        level: 'hard',
        topic: 'Physical Chemistry',
      },
      {
        q: 'Which transition metal compound is coloured?',
        opts: ['ZnSO₄', 'CuSO₄', 'CaCl₂', 'Mg(NO₃)₂'],
        correct: 1,
        explain: 'Cu²⁺ has an incomplete d shell (d⁹); d–d transitions absorb visible light. Zn²⁺ (d¹⁰) and main-group salts are colourless.',
        level: 'moderate',
        topic: 'Inorganic Chemistry',
      },
      {
        q: 'The E⁰ of Zn²⁺/Zn is −0.76 V and Cu²⁺/Cu is +0.34 V. The EMF of the Daniel cell is:',
        opts: ['−1.10 V', '+1.10 V', '+0.42 V', '−0.42 V'],
        correct: 1,
        explain: 'EMF = E⁰(cathode) − E⁰(anode) = 0.34 − (−0.76) = +1.10 V. Copper plates out, zinc dissolves.',
        level: 'hard',
        topic: 'Electrochemistry',
      },
    ],
  },

  maths: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'If f(x) = x³ − 3x + 2, then f′(1) equals:',
        opts: ['0', '1', '3', '−3'],
        correct: 0,
        explain: 'f′(x) = 3x² − 3 ⇒ f′(1) = 3 − 3 = 0. So x = 1 is a stationary point (in fact a local maximum here).',
        level: 'easy',
        topic: 'Calculus',
      },
      {
        q: 'The value of ∫₀^π sin x dx is:',
        opts: ['0', '1', '2', 'π'],
        correct: 2,
        explain: '∫ sin x dx = −cos x; evaluated from 0 to π: (−cos π) − (−cos 0) = 1 + 1 = 2.',
        level: 'easy',
        topic: 'Calculus',
      },
      {
        q: 'The sum of the first 20 terms of the AP 3, 7, 11, … is:',
        opts: ['820', '860', '800', '780'],
        correct: 0,
        explain: 'Sₙ = n/2 [2a + (n−1)d] = 20/2 [6 + 19×4] = 10 × 82 = 820.',
        level: 'moderate',
        topic: 'Algebra',
      },
      {
        q: 'If one root of x² + bx + 12 = 0 is 3, the other root is:',
        opts: ['3', '4', '−4', '6'],
        correct: 1,
        explain: 'Product of roots = c/a = 12 ⇒ other root = 12/3 = 4. (b = −7 in this case.)',
        level: 'moderate',
        topic: 'Algebra',
      },
      {
        q: 'The focus of the parabola y² = 16x is:',
        opts: ['(2, 0)', '(4, 0)', '(8, 0)', '(16, 0)'],
        correct: 1,
        explain: 'Compare with y² = 4ax: 4a = 16 ⇒ a = 4, so the focus is at (4, 0) and the directrix is x = −4.',
        level: 'moderate',
        topic: 'Coordinate Geometry',
      },
      {
        q: 'The angle between the vectors i + j and i − j is:',
        opts: ['0°', '45°', '90°', '180°'],
        correct: 2,
        explain: 'Dot product = 1×1 + 1×(−1) = 0. Perpendicular vectors have zero dot product, so the angle is 90°.',
        level: 'easy',
        topic: 'Vectors & 3D',
      },
      {
        q: 'The distance of the point (2, 3, 6) from the XY-plane is:',
        opts: ['2', '3', '6', '7'],
        correct: 2,
        explain: 'Distance from the XY-plane is |z| = 6. Distances from YZ- and ZX-planes would be |x| = 2 and |y| = 3.',
        level: 'easy',
        topic: 'Vectors & 3D',
      },
      {
        q: 'Two fair dice are rolled. The probability that the sum is 9 is:',
        opts: ['1/6', '1/9', '1/12', '2/9'],
        correct: 2,
        explain: 'Favourable outcomes: (3,6),(4,5),(5,4),(6,3) = 4 out of 36 ⇒ 4/36 = 1/12.',
        level: 'moderate',
        topic: 'Probability',
      },
    ],
  },

  biology: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'The powerhouse of the cell is:',
        opts: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'],
        correct: 2,
        explain: 'Mitochondria perform aerobic respiration and generate ATP — hence “powerhouse”. Plant cells have hundreds of them.',
        level: 'easy',
        topic: 'Cell Biology',
      },
      {
        q: 'Which of the following is a stop codon?',
        opts: ['AUG', 'UAA', 'UGG', 'GUA'],
        correct: 1,
        explain: 'UAA (ochre) signals termination. AUG is the start codon (methionine); UGG codes tryptophan; GUA is valine.',
        level: 'easy',
        topic: 'Genetics',
      },
      {
        q: 'A test cross involves crossing an F₁ hybrid with:',
        opts: ['A dominant parent', 'A recessive parent', 'Another F₁ hybrid', 'A polyploid parent'],
        correct: 1,
        explain: 'Test crossing with the homozygous recessive reveals the F₁ genotype through the phenotypic ratio of offspring.',
        level: 'easy',
        topic: 'Genetics',
      },
      {
        q: 'Enzymes are, chemically, mostly:',
        opts: ['Lipids', 'Carbohydrates', 'Proteins', 'Nucleotides'],
        correct: 2,
        explain: 'Almost all enzymes are proteins (a few catalytic RNAs exist). Their 3D structure creates the active site.',
        level: 'easy',
        topic: 'Cell Biology',
      },
      {
        q: 'The functional unit of the kidney is the:',
        opts: ['Neuron', 'Nephron', 'Alveolus', 'Villus'],
        correct: 1,
        explain: 'Each kidney has about a million nephrons that filter blood and form urine. Neurons are nerve cells; alveoli are lung units.',
        level: 'easy',
        topic: 'Human Physiology',
      },
      {
        q: 'Darwin’s theory of natural selection is best supported by which observation?',
        opts: ['Use and disuse of organs', 'Struggle for existence and differential survival', 'Inheritance of acquired traits', 'Lamarckian inheritance'],
        correct: 1,
        explain: 'Darwin proposed that individuals with advantageous variations survive and reproduce more — differential survival drives evolution.',
        level: 'moderate',
        topic: 'Evolution',
      },
      {
        q: 'Which greenhouse gas contributes most to anthropogenic warming?',
        opts: ['Methane', 'Carbon dioxide', 'Nitrous oxide', 'CFCs'],
        correct: 1,
        explain: 'CO₂ from fossil fuels has the largest total radiative forcing, despite methane’s higher per-molecule warming.',
        level: 'moderate',
        topic: 'Ecology',
      },
      {
        q: 'In a monohybrid cross of two heterozygotes, the phenotypic ratio is:',
        opts: ['1 : 1', '3 : 1', '9 : 3 : 3 : 1', '2 : 1'],
        correct: 1,
        explain: 'Aa × Aa gives 3 dominant : 1 recessive. 9:3:3:1 is the dihybrid ratio; 1:1 arises in test crosses.',
        level: 'moderate',
        topic: 'Genetics',
      },
    ],
  },

  english: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'Choose the correctly punctuated sentence:',
        opts: ['“Where are you going?” she asked.', '“Where are you going”? she asked.', '“Where are you going?” She asked.', 'Where are you going? she asked.'],
        correct: 0,
        explain: 'The question mark belongs inside the quotation, and the reporting clause after it begins with a lowercase word.',
        level: 'easy',
        topic: 'Grammar',
      },
      {
        q: 'The sentence “The roaring lion was chased by the timid rabbit” is an example of:',
        opts: ['Oxymoron', 'Irony', 'Hyperbole', 'Paradox'],
        correct: 1,
        explain: 'Situational irony: the expected outcome (lion dominant) is reversed — the timid rabbit chases the lion.',
        level: 'easy',
        topic: 'Literary Terms',
      },
      {
        q: 'Identify the figure of speech: “The wind whispered through the trees.”',
        opts: ['Simile', 'Personification', 'Onomatopoeia', 'Synecdoche'],
        correct: 1,
        explain: 'A human action (whispering) is attributed to a non-human thing — personification.',
        level: 'easy',
        topic: 'Literary Terms',
      },
      {
        q: 'Choose the word closest in meaning to “ubiquitous”:',
        opts: ['Rare', 'Present everywhere', 'Ancient', 'Powerful'],
        correct: 1,
        explain: 'Ubiquitous means present or found everywhere — e.g., “smartphones are ubiquitous today”.',
        level: 'moderate',
        topic: 'Vocabulary',
      },
      {
        q: 'Choose the grammatically correct option: “Neither of the answers ___ correct.”',
        opts: ['are', 'is', 'were', 'have been'],
        correct: 1,
        explain: '“Neither” is singular, so it takes the singular verb “is”, regardless of the prepositional phrase after it.',
        level: 'moderate',
        topic: 'Grammar',
      },
      {
        q: 'In the sentence “She passed the exam, although she had barely studied”, the underlined clause functions as:',
        opts: ['Relative clause', 'Adverbial clause of concession', 'Noun clause', 'Conditional clause'],
        correct: 1,
        explain: '“Although” introduces concession — it contrasts the passing with the lack of study.',
        level: 'moderate',
        topic: 'Grammar',
      },
      {
        q: 'A passage states: “Sales rose 12% even as costs climbed 20%.” The safest inference is:',
        opts: ['Profits certainly grew', 'Margins likely compressed', 'The company expanded staffing', 'Demand fell in the quarter'],
        correct: 1,
        explain: 'Costs growing faster than sales implies shrinking profit margins — the inference the examiner wants you to draw.',
        level: 'hard',
        topic: 'Reading Comprehension',
      },
      {
        q: '“All roads lead to Rome” is best paraphrased as:',
        opts: ['Rome is easy to reach', 'Different methods can reach the same goal', 'Travel is overrated', 'Rome was well planned'],
        correct: 1,
        explain: 'The idiom means varied approaches can all arrive at the same successful outcome.',
        level: 'hard',
        topic: 'Vocabulary',
      },
    ],
  },

  economics: {
    time: 15,
    outOf: 8,
    questions: [
      {
        q: 'The central problem of every economy is:',
        opts: ['How to increase money supply', 'What, how and for whom to produce', 'How to fix prices', 'How to tax citizens'],
        correct: 1,
        explain: 'Scarcity forces every economy to choose what to produce, how to produce, and for whom to produce.',
        level: 'easy',
        topic: 'Microeconomics',
      },
      {
        q: 'Opportunity cost is best described as:',
        opts: ['The money spent on a purchase', 'The value of the next-best alternative forgone', 'The total cost of production', 'Sunk cost of investment'],
        correct: 1,
        explain: 'Opportunity cost is what you give up to choose one option — the corner-stone of economic thinking.',
        level: 'easy',
        topic: 'Microeconomics',
      },
      {
        q: 'In perfect competition, each firm is a:',
        opts: ['Price maker', 'Price taker', 'Quantity leader', 'Monopolist'],
        correct: 1,
        explain: 'Many small firms sell identical products, so each accepts the market price — any deviation loses all customers.',
        level: 'easy',
        topic: 'Microeconomics',
      },
      {
        q: 'GDP at factor cost differs from GDP at market price mainly because of:',
        opts: ['Depreciation only', 'Net indirect taxes', 'Net factor income from abroad', 'Population growth'],
        correct: 1,
        explain: 'GDP_FC = GDP_MP − net indirect taxes. Only net factor income abroad changes GDP into GNP, not factor cost.',
        level: 'moderate',
        topic: 'Macroeconomics',
      },
      {
        q: 'The fiscal deficit equals:',
        opts: ['Revenue expenditure − revenue receipts', 'Total expenditure − total receipts excluding borrowings', 'Borrowings − interest payments', 'Exports − imports'],
        correct: 1,
        explain: 'Fiscal deficit measures total borrowing needs: total expenditure minus all receipts excluding borrowings.',
        level: 'moderate',
        topic: 'Public Finance',
      },
      {
        q: 'The repo rate is the rate at which:',
        opts: ['Banks lend to customers', 'RBI lends short-term funds to banks against securities', 'RBI borrows from banks', 'Banks lend to each other overnight'],
        correct: 1,
        explain: 'Repo = RBI lending to banks against government securities (the reverse repo is the mirror). It is the RBI’s key policy lever.',
        level: 'moderate',
        topic: 'Macroeconomics',
      },
      {
        q: 'CPI-based inflation targeting in India aims to keep inflation around:',
        opts: ['2% with ±1% band', '4% with ±2% band', '6% fixed', '8% fixed'],
        correct: 1,
        explain: 'The RBI’s mandate: 4% CPI inflation with a tolerance band of 2–6%, set by the Monetary Policy Committee.',
        level: 'hard',
        topic: 'Indian Economy',
      },
      {
        q: 'The mean of 5, 7, 9, 11, 13 and the median are respectively:',
        opts: ['9 and 9', '9 and 10', '10 and 9', '8 and 10'],
        correct: 0,
        explain: 'Mean = 45/5 = 9; the middle value of the ordered set is 9. Symmetric data gives mean = median.',
        level: 'moderate',
        topic: 'Statistics',
      },
    ],
  },
};
